package com.abctreinamentos;

// Generated Jan 31, 2017 4:01:41 PM by Hibernate Tools 4.3.1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name = "CURSO")
public class Curso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cdcurso;
	private String nome;
	private double valor;
	private String url;

	public Curso() {
	}

	public Curso(int cdcurso, String nome, double valor, String url) {
		this.cdcurso = cdcurso;
		this.nome = nome;
		this.valor = valor;
		this.url = url;
	}

	@Id
	@Column(name = "CDCURSO", unique = true, nullable = false)
	public int getCdcurso() {
		return this.cdcurso;
	}

	public void setCdcurso(int cdcurso) {
		this.cdcurso = cdcurso;
	}

	@Column(name = "NOME", nullable = false, length = 80)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "VALOR", nullable = false, precision = 22, scale = 0)
	public double getValor() {
		return this.valor;
	}

	public void setValor(double valor) {
		this.valor = valor;
	}

	@Column(name = "URL", nullable = false, length = 80)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public String toString() {
		return "Curso [cdcurso="+cdcurso+" nome="+nome+" valor="+valor+" url="+url+"]";
	}
}
