package com.abctreinamentos;

// Generated Jan 31, 2017 4:01:41 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "PAGAMENTO")
public class Pagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PagamentoId id;
	private String datainscricao;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, String datainscricao) {
		this.id = id;
		this.datainscricao = datainscricao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cpf", column = @Column(name = "CPF", nullable = false, length=14)),
			@AttributeOverride(name = "cdcurso", column = @Column(name = "CDCURSO", nullable = false)) })
	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	@Column(name = "DATAINSCRICAO", nullable = false, length = 10)
	public String getDatainscricao() {
		return this.datainscricao;
	}

	public void setDatainscricao(String datainscricao) {
		this.datainscricao = datainscricao;
	}

	@Override
	public String toString() {
		return "Pagamento [cpf="+id.getCpf()+" cdcurso="+id.getCdcurso()+" data_inscricao="+datainscricao+"]";
	}
}
